sonar.projectKey=Dmolight01_codefactory_20261
sonar.organization=dmolight01

sonar.host.url=https://sonarcloud.io

# Rutas del código
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Ruta del reporte JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
